# Generated by Django 3.2 on 2021-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfoliosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=80)),
                ('sub_title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(blank=True, to='members.MemberModel')),
            ],
            options={
                'verbose_name_plural': 'PORTFOLIOS',
            },
        ),
    ]
